#bcmsh show portmap > portmap.txt
#show interfaces status >interfaces.txt

function getPortId() {
lanes=$(show interfaces status | awk '{print $2}' | awk -F, '{print $1}')
portMap=$(bcmcmd "show portmap")

for lane in $lanes
do
        echo $portMap | grep "$lane" | awk -v LANE="$lane" '
        {
                #printf("\nProcessing %d, %s\n ", LANE, $0);
                #if ($4==LANE){print $3 ", " $4}
                if ($4==LANE){printf("%d ", $3);}
        }'
done
#TODO classify the port by speed

}

#lanes.txt was generated by getPortId
lanesfile=lanes.txt

if [ "$1" != "" ]; then 
    lanesfile="$1"
fi

#TODO add profile by speed(25G,100G,200G,400G)
awk 'BEGIN{line=1}
{

  if (line == 1) {
          printf("bsh -c \"lt PC_AUTONEG_PROFILE insert PC_AUTONEG_PROFILE_ID=3 NUM_LANES=4 ADVERT_SPEED=200000 AUTONEG_MODE=PC_PHY_AUTONEG_MODE_CL73 FEC_MODE=PC_FEC_RS544_2XN MEDIUM_TYPE=PC_PHY_MEDIUM_COPPER\"\n")

    for (i=1; i <= NF; i++) {
        printf("bsh  -c \"lt PC_PORT update PORT_ID=%d PC_AUTONEG_PROFILE_ID[0]=3 NUM_VALID_AN_PROFILES=1 AUTONEG=1\"\n", $i)
    }
    line++
  } else {

          printf("bsh  -c \"lt PC_AUTONEG_PROFILE insert PC_AUTONEG_PROFILE_ID=2 NUM_LANES=8 ADVERT_SPEED=400000 AUTONEG_MODE=PC_PHY_AUTONEG_MODE_MSA FEC_MODE=PC_FEC_RS544_2XN MEDIUM_TYPE=PC_PHY_MEDIUM_COPPER\"\n")

    for (i=1; i <= NF; i++) {
        printf("bsh  -c \"lt PC_PORT update PORT_ID=%d PC_AUTONEG_PROFILE_ID[0]=2 NUM_VALID_AN_PROFILES=1 AUTONEG=1\"\n", $i)
    }
  }
}' < $lanesfile
